Adding initial event info for 2020-09-29
RSE-leaders/SORSE20 pull request #320
Opened 2020-09-08 18:57 UTC by jcohen02

This PR includes the event information for the event scheduled for 2020-09-29.

The event is awaiting an ID and Indico registration link and there will likely be a couple of other updates to be made but in terms of making the basic event information available, this is ready to be merged once an ID and registration link are added.

2020-09-08 19:40 UTC, Chilipp requested changes
hey @jcohen02! thanks a lot for your work here. The failures are totally not your fault. It's a python 3.6 thing, it cannot decode characters such as `’`. So I replaced them here.

 @vsoch: Do you think we can adapt the pdf-generation action to use python 3.7 (or 3.8) instead of 3.6? Then this would not be a problem anymore.

2020-09-08 19:40 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +    - name: King’s Digital Laboratory, King's College London, London, UK
```suggestion
    - name: King's Digital Laboratory, King's College London, London, UK
```

2020-09-08 19:40 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +This SORSE event describes King’s Digital Lab (KDL), a Research Software Engineering lab operating within the Faculty of Arts and Humanities at King’s College London (UK). The KDL team of 18 project
```suggestion
This SORSE event describes King's Digital Lab (KDL), a Research Software Engineering lab operating within the Faculty of Arts and Humanities at King's College London (UK). The KDL team of 18 project managers, analysts, designers, engineers, and systems managers specialise in arts & humanities, cultural heritage, and creative industries research and development. The talk will provide a current state overview of the lab, and describe our RSE HR roles (see [https://zenodo.org/record/2564790](https://zenodo.org/record/2564790)) and a relatively recent trial initiative that defines the different ways the team can contribute to research. A more technically-oriented overview of our ongoing work in refining the fundamental components of  KDL Software Development Lifecycle (see https://github.com/kingsdigitallab/sdlc-for-rse/) will also be provided, including descriptions of our modelling workflows, processes, and efforts to increase sustainability, reproducibility, and research data management best practice ([https://zenodo.org/record/3361580#.X09x6mdKhhE](https://zenodo.org/record/3361580#.X09x6mdKhhE)).
```

2020-09-08 19:40 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +**James Smithies** is Director of King’s Digital Lab & Reader and Deputy Director of eResearch at King’s College London. He was previously Senior Lecturer in Digital Humanities and Associate Director
```suggestion
**James Smithies** is Director of King's Digital Lab & Reader and Deputy Director of eResearch at King’s College London. He was previously Senior Lecturer in Digital Humanities and Associate Director of the UC CEISMIC Digital Archive at the University of Canterbury, New Zealand. He has worked in the government and commercial IT sectors as a technical writer and editor, business analyst, and project manager. In 2017 he published a monograph for Palgrave Macmillan titled [Digital Humanities and the Digital Modern](https://www.palgrave.com/gp/book/9781137499431). James is interested in applied and theoretical digital humanities, including data analysis, minimal computing, digital archives, modelling and virtual worlds. He has subsidiary interests in critical and media theory, and postphenomenology. His historical work focuses on the history of ideas, technology (including but not limited to computing), and literature. See his [personal website](https://jamessmithies.org/) for more information about his work.
```

2020-09-08 19:40 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +**Arianna Ciula** is Deputy Director & Senior Research Software Analyst at King’s Digital Lab. She has broad experience in digital humanities research and teaching, research management, and digital r
```suggestion
**Arianna Ciula** is Deputy Director & Senior Research Software Analyst at King's Digital Lab. She has broad experience in digital humanities research and teaching, research management, and digital research infrastructures. She holds a PhD in Manuscript and Book Studies (digital palaeography, University of Siena), an MA in Applied Computing in the Humanities (King's College London) and a BA Hons in Communication sciences (computational linguistics, University of Siena). She worked at King's in the past as Research Associate (Centre for Computing in the Humanities, 2003-2009). From 2009 to 2012, she worked as Science officer at the European Science Foundation (Humanities) and from 2013 she worked as Research Facilitator at the University of Roehampton for three years..
```

2020-09-08 19:40 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +Her personal research interests focus on the modelling of scholarly digital resources related to primary sources. She lectured and published on humanities computing, in particular on digital manuscri
```suggestion
Her personal research interests focus on the modelling of scholarly digital resources related to primary sources. She lectured and published on humanities computing, in particular on digital manuscript studies and editing; she has organised conferences and workshops in digital humanities, and is an active member of its international community. She was co-PI in the project "[Modelling between Digital and Humanities: Thinking in Practice](http://modellingdh.eu/)" funded by the Volkswagen Foundation (2016-18). See list of [publications](https://kclpure.kcl.ac.uk/portal/en/persons/arianna-ciula(8b156ef5-c75d-46a7-9be9-2eb2a4666f31)/publications.html).
```

2020-09-08 20:11 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +title: "Digital Humanities RSE: King’s Digital Lab as experiment and lifecycle"
```suggestion
title: "Digital Humanities RSE: King's Digital Lab as experiment and lifecycle"
```

2020-09-08 20:12 UTC, Chilipp commented on _events/talks/event-ID_UNKNOWN.md
> +**James Smithies** is Director of King's Digital Lab & Reader and Deputy Director of eResearch at King’s College London. He was previously Senior Lecturer in Digital Humanities and Associate Director
```suggestion
**James Smithies** is Director of King's Digital Lab & Reader and Deputy Director of eResearch at King's College London. He was previously Senior Lecturer in Digital Humanities and Associate Director of the UC CEISMIC Digital Archive at the University of Canterbury, New Zealand. He has worked in the government and commercial IT sectors as a technical writer and editor, business analyst, and project manager. In 2017 he published a monograph for Palgrave Macmillan titled [Digital Humanities and the Digital Modern](https://www.palgrave.com/gp/book/9781137499431). James is interested in applied and theoretical digital humanities, including data analysis, minimal computing, digital archives, modelling and virtual worlds. He has subsidiary interests in critical and media theory, and postphenomenology. His historical work focuses on the history of ideas, technology (including but not limited to computing), and literature. See his [personal website](https://jamessmithies.org/) for more information about his work.
```

2020-09-08 20:13 UTC, Chilipp approved these changes

2020-09-08 20:14 UTC, Chilipp commented
@eileen-kuehn: Could you please provide a registration url and an event-id?

- [ ] registration url inserted
- [ ] event-ID changed

2020-09-08 20:19 UTC, vsoch commented
I'm not sure what action you are asking for on the pdf-generator - it installs python3 and uses pandoc to generate the output, and @jcohen02 reports that all is working - if you are able to find the issue [in the entrypoint](https://github.com/rseng/pdf-generator/blob/master/entrypoint.sh) please let me know and I'd be happy to create a branch for testing.

2020-09-08 20:20 UTC, Chilipp commented
> it seemed to generate a PDF without complaining about the quote characters.

yep @jcohen02, this is probably because you used the default settings which does not extract any metadata from the markdown file. If you want to mimick the PDF generation locally, you need to run the docker build as such:

```bash
cp _events/talks/event-ID_UNKNOWN.md ci/
docker run --env-file ci/env.txt -it -v `pwd`:/github/workspace rseng/pdf-generator
``` 

This should fail with the same error as in the github action (well, now it works, as I changed the problematic characters)

2020-09-08 20:32 UTC, Chilipp commented
> if you are able to find the issue in the entrypoint please let me know and I'd be happy to create a branch for testing.

see https://github.com/rseng/pdf-generator/issues/6, is it okay that way @vsoch?

2020-09-08 20:33 UTC, Chilipp commented
@jcohen02, the PDF generation is failing because it's a forked PR. We'll do this later (actually it should not attempt to open a PR for forks, sorry about that)

2020-09-09 07:41 UTC, eileen-kuehn reviewed
I added the correct indico URL for registration and did open registration already.
I still need some information about the actual schedule that I can properly fill the timetable.

The registered ID for the event is *27* so the file name should become `event-027.md`. @jcohen02, could you change it?

2020-09-09 07:41 UTC, eileen-kuehn commented on _events/talks/event-ID_UNKNOWN.md
> +registration_url: https://indico.scc.kit.edu/event/ID_UNKNOWN/
```suggestion
registration_url: https://indico.scc.kit.edu/event/923/
```

2020-09-09 07:41 UTC, eileen-kuehn commented on _events/talks/event-ID_UNKNOWN.md
> +    - name: King's Digital Laboratory, King's College London, London, UK
```suggestion
    - name: King's Digital Laboratory, King's College London, UK
```

2020-09-09 07:44 UTC, Chilipp commented
> The registered ID for the event is 27 so the file name should become event-027.md. @jcohen02, could you change it?

I am not @jcohen02, but I changed it :wink:

2020-09-09 08:11 UTC, jcohen02 commented
Thanks for your work investigating the issues here @Chilipp, and for changing the event ID 🙂

2020-09-09 08:51 UTC, Chilipp commented
alright, when the CI finishes, we can merge this PR. Thanks a lot @jcohen02 (although for your patience :sweat_smile:)

2020-09-09 08:56 UTC, jcohen02 commented
No problem @Chilipp, not quite as straightforward as we had all hoped but a useful exercise nonetheless. Thanks for your help in resolving the issues.

2020-09-09 08:58 UTC, Chilipp commented
there seems to be a problem with the site of personal website of @tscheypidi (https://www.pik-potsdam.de/research/members/dietrich) which is why the link checking in the CI is failing. But I suspect, PIK will resolve this soon, so I'll merge this PR despite the failure (see also #327)

2020-09-09 08:59 UTC, merged

2022-05-11 15:04 UTC, PYTHON3610 commented
I'm new to python and programming where and what can I do here

2022-05-11 17:09 UTC, vsoch commented
hey @PYTHON3610 ! I think this event is now passed so we don't have further work on this particular site (until it or a similar event happens again) but if you want to join the society's slack (instructions here) https://society-rse.org/join-us/ you can probably get notified when there is a new/future effort to make something.

2022-05-12 11:28 UTC, PYTHON3610 commented
Thanks you for the response and I will join your societies slack

Sent from my iPhone

> On 11 May 2022, at 5:10 PM, Vanessasaurus ***@***.***> wrote:
> 
> ﻿
> hey @PYTHON3610 ! I think this event is now passed so we don't have further work on this particular site (until it or a similar event happens again) but if you want to join the society's slack (instructions here) https://society-rse.org/join-us/ you can probably get notified when there is a new/future effort to make something.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.